### ISSUE TITLE
Problem with concept relations representation

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#12]
Below I show the current concept relations for "SIBLING". Naturally, SIBLING should only have outgoing edges in the "is broader as x" relation.

The concept relations for sister vs. sibling and brother vs. sibling are displayed in the source as:

```text
1640	SIBLING	narrower	1262	BROTHER
1263	SISTER	broader	1640	SIBLING
```

So when preparing this, I was reading this as: concept SIBLING, narrower is "BROTHER", and  concept "SISTER", broader is "SIBLING".

Yet the concepticon website displays this currently as in the image below:

![bildschirmfoto_2016-04-04_11-16-26](https://cloud.githubusercontent.com/assets/2916210/14243573/b5669f20-fa56-11e5-8ef4-5ea24e01d8d9.png)

So does it currently assume that broader/narrower follows a certain direction?

This relates also to the graph on the first page, since it displays the arrows identically, based on the json representation.

We either have a bug in the definition of concept relations in concepticon-data, or a bug in the display of the concept relations.

**Comment by xrotwang** [comment]
I think this is only a display problem. For me, our `broader` and `narrower` relations are the same as the corresponding [SKOS semantic relations](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#semantic-relations). So maybe adding a prefix `skos:` when displaying relation names would help to make this clear? Regarding the graph: I guess it would be clearer to have edges only representing one of the two inverse relations. This could be done when computing the JSON data for the graph.

**Comment by LinguList** [comment]
ah, I see, sorry, it is really just the display! Yes, and in the graph, it should be just that we only show broader. All is fine then. But since sigma displays arrows very small, I just excluded them anyway from the graph on the first page, since they have not yet fixed their code to allow for individual arrow sizes, and too thick edges are also ugly, so we can as well just display it in an undirected fashion, and users will guess that there are relations.

As to display: could we somehow arrange this to always show, say "concept current" isBroaderAs concept x and concept y isBroaderAs concept current? This would be less confusing, I guess.

**Comment by LinguList** [comment]
the easiest way to fix this is to just sort the concept relations differently on the concepticon-data curation site:

https://github.com/LinguList/concepticon-data/blob/0b6096e27cb4e73f8f950adcbd62880223c07c00/concepticondata/conceptrelations.tsv
