### ISSUE TITLE
PDF-URL for sources: is it possible to change "blob" to "raw"?

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#15]
I guess it is this line which decides how to represent the source-link for PDF files:

https://github.com/clld/concepticon/blob/master/concepticon/templates/source/detail_html.mako#L14

However, currently, the PDF is displayed as github-link, and it might be more useful to represent it as either a link to an internal resource (if all data is anyway uploaded to the server), or as a link to github raw addresses, like replacing this link:

* https://github.com/clld/concepticon-data/blob/master/concepticondata/sources/Gregersen1976.pdf

with this link:

* https://github.com/clld/concepticon-data/raw/master/concepticondata/sources/Gregersen1976.pdf

For my user-experience, when I click on "PDF" I expect almost a direct download, but when looking at github, it may confuse the users.

**Comment by xrotwang** [comment]
Yes. I think we should upload the PDFs, and link to the files directly.
