### ISSUE TITLE
Kessler-2001-200 yields INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#18]
dunno why, but this list was newly added in 1.01...

**Comment by xrotwang** [comment]
The file [conceptlists.tsv](https://github.com/clld/concepticon-data/blob/62d947e10420539b055fdbdc89f5aadfadb750c9/concepticondata/conceptlists.tsv) was not well formed, line 2 has one too many tabs. The default behaviour when reading such a line into `dict`s is to add additional data to a `dict` key `None`. This key in turn resulted in a `null` being present in the database, which caused the server error.
I'm preparing a PR for concepticon-data fixing the problem and adding tests to avoid regression.

**Comment by LinguList** [comment]
Oh, sorry! So there is, I guess still another check we should add to the
data? Testing all files for malformedness?

**Comment by xrotwang** [comment]
Yeah, I have this covered, will be in PR.

**Comment by LinguList** [comment]
super!
