### ISSUE TITLE
"specific" tag is now added to all concept lists

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#20]
I think it is due to this line:

* https://github.com/clld/concepticon/blob/master/concepticon/scripts/initializedb.py#L132

```python
        for tag in split(cl['TAGS']):
            DBSession.add(models.ConceptlistTag(
                conceptlist=conceptlist, tag=data['Tag'][tag]))
        else:
            DBSession.add(models.ConceptlistTag(
                conceptlist=conceptlist, tag=data['Tag']['specific']))
```

Where the "else" answers to the "for" without checking whether the tag is empty (and specific is reserved for strange lists). So modifying to:

```python
        for tag in split(cl['TAGS']):
            DBSession.add(models.ConceptlistTag(
                conceptlist=conceptlist, tag=data['Tag'][tag]))
        if not split(cl['TAGS']):
            DBSession.add(models.ConceptlistTag(
                conceptlist=conceptlist, tag=data['Tag']['specific']))
```
or similar should solve this (but I don't know whether this is the best way to proceed.

**Comment by xrotwang** [comment]
Ah sorry. I messed up this thing. The `else` branch is run when no `break` occurs in the `for` loop, so always in this case. I'll clean this up.

**Comment by LinguList** [comment]
No problem. At some point I should stop looking at the data, since I found some more errata in concepticon-data, based on wrong links ("you" can be "thou" or "you"), but at some point, one needs to give it a rest, I guess...

**Comment by xrotwang** [comment]
@LinguList Dunno if this is the best way to deal with such cases, but it should be transparent enough for the moment: https://github.com/clld/concepticon/releases

**Comment by LinguList** [comment]
I think this is just fine.
