### ISSUE TITLE
List subsets and maximal coverage sets for download in CSV?

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#22]
Given that it's quite straightforward to make the list comparisons, I was asked whether we could offer lists for download in such a way, that they are merged, and maybe directly converted to spreadsheet formats. This would be a click-interface, where one selects two or three lists (I guess we should restrict it) and then selects an operation (merge, coverage).

This might be an interesting service for field-workers, and we could further flag the concepticon as tool for language documentation (which is surely also is).

**Comment by xrotwang** [comment]
Should be doable. What exactly does merge mean, though?
Am 07.10.2016 07:32 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
I'd say: either, you want only the subset, that is, what is left in all
lists (as the current command line overlap states). An alternative would
be: make a list that contains the other lists all as subset. A yes: its
intersection vs. union.

**Comment by LinguList** [comment]
With the `pyconcepticon` api, and our tutorials, this is obsolete, as people should just use `pyconcepticon` for this.
