### ISSUE TITLE
Shortcut for links to bib in concept set description

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon#24]
There should be a pattern - analogous to how we [handle links to concept lists](https://github.com/clld/concepticon/blob/master/concepticon/util.py#L18) - for link to the bibliography.

**Comment by LinguList** [comment]
the result would be: http://bibliography.lingpy.org/evobib.php?key= plus the AuthorYear

**Comment by xrotwang** [comment]
Or http://concepticon.clld.org/sources/beaufils2015 ? And maybe have a link to evobib from there?

**Comment by LinguList** [comment]
would also be possible, yet there are some references to other sources not in our references. Yet one could easily filter them out and add them to our references.bib, and then, the link to evobib would even not be needed.

**Comment by xrotwang** [comment]
I think I'd prefer this, since external links for stuff that's available within the app seem a bit weird and unintuitive.

**Comment by LinguList** [comment]
completely okay with me, its' just confusing for the users.

**Comment by LinguList** [comment]
Oh, just saw, when I wanted to close this, that the `:bib:AuthorYear` is not yet linking to the source, although we have all sources already in the data. Should we change all `:bib:*` instances, or rather add the support to link to the  http://concepticon.clld.org/sources/AuthorYear in a later version?

**Comment by xrotwang** [comment]
Sorry, forgot to deploy the latest code to the server. Now these links should work. If not, it's a bug.
