### ISSUE TITLE
Change statement on ontological categories.

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#26]
As @haspelmath pointed out, we should change the statement on ontological categories in about.mako, maybe like this:

> The ontological categories are mostly added for practical reasons of
allowing us to order and link the concepts more quickly. They should not
be taken as a literal statement that we believe that they really exist
as such.

**Comment by haspelmath** [comment]
Or like this:

The ontological categories are mostly added for practical reasons of
allowing us to order and link the concepts more quickly. They should not
be taken as a serious semantic classification of the concept lists.
