### ISSUE TITLE
Update statement on funding for 1.1

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#28]
The funding statement for Version 1.1. (List, Cysouw, Greenhill, and Forkel) should look something like this this time, I'd say:

```
<p>
  The development of the Concepticon in its current version was supported by the
  DFG research fellowship grant 261553824 <a href="http://gepris.dfg.de/gepris/projekt/261553824?language=en">Vertical and lateral aspects of
  Chinese dialect history</a> (JML, 2014-2016) and the ERC starting grant 240816
  <a href="http://quanthistling.info/">Quantitative modelling of historical comparative linguistics</a> (MC, JML, 2014-2016), the ERC starting grant 715618 <a href="http://calc.digling.org">Computer-Assisted Language Comparison</a> (JML, 2017-now), the 
Australian Research Council’s Discovery Projects funding scheme (project
number DE 120101954) and the ARC Center of Excellence for the Dynamics of Language grant
CE140100041 (SJG).
  As part of the <a href="http://clld.org">CLLD Project</a> 
  and the <a href="http://glottobank.org">Glottobank Project</a>, 
  the work was further supported by the Max Planck Society, the Max Planck Institute for the Science of Human
  History, and the Royal Society of New Zealand (Marsden Fund grant 13-UOA-121,
  RF). All support is gratefully acknowledged. 
</p>
```

@SimonGreenhill, could you review and maybe add links to your projects, as well as dates from when to when?

**Comment by SimonGreenhill** [comment]
<p>
The development of the Concepticon in its current version was supported by the
DFG research fellowship grant 261553824 <a href="http://gepris.dfg.de/gepris/projekt/261553824?language=en">Vertical and lateral aspects of Chinese dialect history</a> (JML, 2014-2016) and the ERC starting grant 240816
  <a href="http://quanthistling.info/">Quantitative modelling of historical comparative linguistics</a> (MC, JML, 2014-2016), the ERC starting grant 715618 <a href="http://calc.digling.org">Computer-Assisted Language Comparison</a> (JML, 2017-now), the Australian Research Council’s Discovery Projects funding scheme (project
number DE 120101954, SJG, 2012-2016) and the ARC Center of Excellence for the Dynamics of Language grant
CE140100041 (SJG, 2015-).
  As part of the <a href="http://clld.org">CLLD Project</a> 
  and the <a href="http://glottobank.org">Glottobank Project</a>, 
  the work was further supported by the Max Planck Society, the Max Planck Institute for the Science of Human
  History, and the Royal Society of New Zealand (Marsden Fund grant 13-UOA-121,
  RF). All support is gratefully acknowledged. 
</p>

**Comment by LinguList** [comment]
I just decided, we should make a table, will post here soon (so people can say which grant was helping in which period to which person).

**Comment by LinguList** [comment]
Period    | Grant Name                                                     | Grant Type                                        | Funding Agency                                        | Grant Number | Beneficiaries
---       | ---                                                            | ---                                               | ---                                                   | --- | ---
2012-2014 | *Quantitative modelling of historical-comparative linguistics* | ERC Starting Grant                                | European Research Council                             | 240816       | MC, JML
2015-2016 | *Vertical and lateral aspects of Chinese dialect history*      | Research Fellowship                               | German Research Council                               | 261553824    | JML
2017-now | [*Computer-Assisted Language Comparison*](http://calc.digling.org)      | Research Fellowship                               | German Research Council                               | 261553824    | JML
2012-2016 |                                                                | ARC Discovery Projects                            | Australian Research Council                           | DE 120101954 | SJG
2015-now  |                                                                | Center of Excellence for the Dynamics of Language | Australian Research Council                           | CE140100041  | SJG
2014-2017 | [Glottobank Project](http://glottobank.org)                                             | Marsden Fund                                      | Royal Society of New Zealand                          | 13-UOA-121   | SJG, JML, RF
2014-now  | [Glottobank Project](http://glottobank.org)                                             |                                                   | Max Planck Institute for the Science of Human history |              | SJG, JML, RF
2014-2017 | [CLLD Project](http://clld.org)                                                   |                                                   | Max Planck Society                                    |              |

**Comment by LinguList** [comment]
See here for the update: https://github.com/clld/concepticon-data/blob/master/CONTRIBUTORS.md if there's something to change, or you are against the table, please let me know or modify directly on Concepticon.

**Comment by SimonGreenhill** [comment]
ok, I've added the extra details.
