### ISSUE TITLE
Long tables break information sidebar

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon#37]
See for example:

https://concepticon.clld.org/contributions/Luniewska-2016-299

Tested with Firefox 67.0.2. Proposal: Update `.dataTables_wrapper` to account for width to make CSS `relative` work properly.

**Comment by LinguList** [comment]
How's the html/css structured? In the new flex and grid schemes, this may be easier to realize, right?

**Comment by xrotwang** [comment]
I think we can live with this very special list being displayed in a very special way.
