### ISSUE TITLE
Broken PDF/source links

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon#38]
E.g. https://concepticon.clld.org/contributions/Swadesh-1960-215, `Swadesh's paper from 1955` links to `http://localhost/sources/swadesh1955`. Happened for `/contribution` links as well.

We've got a lot of those:

```sql
select pk, id from contribution
where description LIKE '%localhost%'
```

|pk|id|
|--|--|
|1|Walworth-2018-215|
|5|Sun-1991-1004|
|6|Robinson-2012-398|
|8|Hill-2017-240|
|9|Serva-2012-200|
|10|Bender-1971-99|
|11|Dellert-2017-1016|
|13|Backstrom-1992-210a|
|14|Backstrom-1992-210b|
|16|Bowern-2017-348|
|17|Kingsada-1999-303|
|18|Calude-2011-200|
|20|Daniels-2016-85|
|21|Swadesh-1964-100|
|22|Swadesh-1960-215|
|23|Wilkins-1996-75|
|25|Peiros-1999-100|
|26|Campbell-1999-100|
|31|Hooley-1971-128|
|32|Rea-1958-100|
|41|Kessler-2001-200|
|33|Mennecier-2016-183|
|34|Liu-2007-201|
|35|Cysouw-2006-110|
|36|Deepadung-2015-100|
|37|List-2016-57|
|38|List-2016-180|
|42|Gregersen-1976-217|
|43|Sato-2002-200|
|44|Lee-2013-200|
|47|Heggarty-2005-30a|
|48|Heggarty-2005-30b|
|50|Pozdniakov-2014-100b|
|51|Alpher-1999-151|
|52|Hale-1961-100|
|53|OGrady-1969-100|
|54|Sidwell-2015-200|
|56|Blust-1981-200|
|59|Bennett-1976-100|
|60|Bennett-1976-50a|
|61|Bennett-1976-50b|
|62|Grollemund-2015-100|
|71|Mann-1998-406|
|64|Ogden-1930-100|
|67|Mitterhofer-2013-95|
|68|Mitterhofer-2013-355|
|69|Mitterhofer-2013-300|
|70|Luqman-2010-65|
|73|Lin-2010-89|
|74|Zheng-2007-86|
|76|Wang-2006-200|
|78|Wang-2004-200|
|79|Wang-2004-95|
|80|Wang-2004-100a|
|81|Wang-2004-100b|
|82|He-2010-207|
|83|Chen-1996-200|
|84|Chen-1996-100a|
|85|Chen-1996-100b|
|89|Calero-2002-15|
|90|Forster-2006-100|
|92|Wichmann-2010-40|
|93|List-2014-1280|
|94|Urban-2011-160|
|95|Borin-2015-1532|
|96|Youn-2016-22|
|97|Kassian-2010-116|
|99|Mann-2004-210|
|100|Trask-1996-207|
|101|Trask-1996-100|
|103|Mann-2004-209|
|104|Nahhas-2006-100|
|105|Comrie-1977-207|
|106|Bowern-2008-207|
|107|Swadesh-1971-100|
|108|Wiktionary-2003-207|
|109|Gudschinsky-1956-200|
|110|Samarin-1967-218|
|111|Holman-2008-100|
|112|Swadesh-1960-100a|
|113|Swadesh-1960-200|
|115|Starostin-1991-110|
|116|Swadesh-1955-100|
|118|Yakhontov-1991-100|
|119|Samarin-1967-100|
|122|Pallas-1789-285|
|133|Yakhontov-1991-35|
|123|Pallas-1786-441|
|124|Ardila-2007-40|
|126|Peust-2013-54|
|127|Pozdniakov-2014-100a|
|129|Swadesh-1955-215|
|134|Starostin-2010-50|
|214|Larson-1972-68|
|137|Trask-2000-15|
|138|Beaufils-2015-18|
|139|Dolgopolsky-1964-15|
|140|Holman-2008-40|
|141|Shevoroshkin-1991-23|
|143|Yakhontov-1991-65|
|203|Miedema-1985-40|
|144|Swadesh-1960-100b|
|145|Ringe-2002-333|
|146|Dyen-1992-200|
|147|Dunn-2012-207|
|148|McMahon-2005-30|
|149|McMahon-2005-23|
|150|Buck-1949-1108|
|215|Heeschen-1978-104|
|151|Dyen-1964-154|
|152|Pagel-2007-200|
|153|Kassian-2015-50|
|154|Hattori-1973-200|
|155|Hattori-1961-236|
|156|Lee-2011-211|
|157|Nagaraja-2013-200|
|159|Dyen-1964-196|
|171|Nelson-2001-89|
|160|Tryon-1983-200|
|161|Tryon-1983-324|
|163|Miller-1994-281|
|164|Thomas-1960-168|
|165|Wilson-1969-35|
|166|McElhanon-1967-140|
|168|Bowern-2011-204|
|169|Bowern-2012-189|
|170|Bowern-2012-205|
|172|Zorc-1974-100|
|173|Mallory-2006-100|
|175|Struve-2014-100|
|176|Heggarty-2005-150|
|177|Cross-1964-241|
|180|Kitchen-2009-95|
|181|Woodward-1991-100|
|182|Woll-2010-301|
|183|Matisoff-1978-200|
|184|Benedict-1976-100|
|185|SatterthwaitePhillips-2011-50|
|187|Mann-2004-500|
|188|Mann-2004-118|
|189|SIL-1980-281|
|190|SIL-2002-436|
|192|Marsden-1782-50|
|193|Krisadawan-2000-210|
|194|SatterthwaitePhillips-2011-423|
|195|Galucio-2015-90|
|196|Galucio-2015-100|
|197|Galucio-2015-28|
|198|Galucio-2015-34|
|199|Syrjaenen-2013-226|
|200|Wheeler-2015-102|
|206|Bromley-1967-111|
|218|Gampe-2017-48|
|220|Pagel-2018-200|
|222|Bengtson-2017-12|
|223|Kibrik-2012-122|
|225|Kolipakam-2018-100|
|228|Carling-2017-104a|
|229|Carling-2017-209b|

**Comment by xrotwang** [comment]
Ah, that's a problem here https://github.com/clld/concepticon/blob/cdd22649d6c19bb6a8e8c804aac9faff1e30137a/concepticon/scripts/initializedb.py#L273
The request object passed into this function assumes a locally running app.
