### ISSUE TITLE
Release CLLD app with v2.4.0 tag and redeploy

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon#45]

**Comment by xrotwang** [comment]
I think that's not really necessary anymore. The authoritative data is the
data repos release, so there's no need to be able to reconstruct exactly
how the data looked on the web for a given release.

Christoph Rzymski <notifications@github.com> schrieb am Mo., 2. Nov. 2020,
09:37:

**Comment by chrzyki** [comment]
Alright, then we can update RELEASING.

The version tag in the footer on https://concepticon.clld.org will then mismatch the data version. Is that a problem?

**Comment by xrotwang** [comment]
A bit of cognitive dissonance is ok, yes :)

Christoph Rzymski <notifications@github.com> schrieb am Mo., 2. Nov. 2020,
09:42:
