### ISSUE TITLE
Align concepticon RDF with BabelNet?

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon#5]
We might consider aligning our RDF model with the [one chosen](http://www.w3.org/2015/09/bpmlod-reports/multilingual-dictionaries/) for http://babelnet.org

**Comment by LinguList** [comment]
What would that mean in concrete? Or, is that something that can be quickly done? Sorry for my lack in understanding of RDF...

*Linking* to babelnet is something that should be done anyway, ideally, I think, although we don't know when somebody will find time to go through our now 2400 concepts...

**Comment by xrotwang** [comment]
It would just mean that we type things we declare as `owl:sameAs` with anything in babelnet the same way, they do. E.g. a concepticon concept set should be a `skos:Concept`, I guess.

**Comment by LinguList** [comment]
A, I see, that seems to make sense.
