### ISSUE TITLE
Modify first page on Web-Release with impressive Graph figure

### ISSUE THREAD

**Issue by LinguList** [clld/concepticon#8]
It is very simple to use lightweight JS apps to make nice graph animations using HTML5 and the canvas stuff. I think, in order to make the concepticon website more appealing when opening it, it would be nice to have some network, be it that it is really animated, be it as gif, illustrating some relations between concepts, or be it in a static form. Currently, I think that the text does not necessarily make it clear to newbies on the website what it is actually about.

**Comment by xrotwang** [comment]
@LinguList ok. I have [sigma.js](http://sigmajs.org/) integrated and running locally. What graph would you suggest? The graph of all concept set relations is a bit too disconnected to be impressive.

**Comment by LinguList** [comment]
Maybe, the kinship-relations, since they are heavily interconnected? Do
you have the graph ready for that part? I used it in the paper.

**Comment by xrotwang** [comment]
I just [committed](https://github.com/clld/concepticon/commit/520c734def5ebd646e8beba74d51bd1ab122ceb2) functionality to display a graph of kinship terms on the home page - below the "Concept sets" header. I think it would require at least a line of explanation/motivation, though.

**Comment by LinguList** [comment]
What about:

```
In our Concepticon, we link Concept Sets by assigning simple relations
like "broader" and "narrower". Yet even these simple relations can get
very complex, as you can see from the network that shows the major
kinship relations which are linked to the Concept Set "SIBLING".
```

Maybe it could be even shorter, I'll keep thinking...

**Comment by LinguList** [comment]
I guess we can close this now, since we have a nice figure on the first page.
